{% set name = "CarveWe" %}
{% set version = GIT_DESCRIBE_TAG.lstrip('v') if GIT_DESCRIBE_TAG else "0.0.0" %}
{% set buildstr = "g" + GIT_DESCRIBE_HASH[:7] if GIT_DESCRIBE_HASH else "local" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ryanreyn/CarveWe.git
  git_rev: {{ GIT_DESCRIBE_TAG if GIT_DESCRIBE_TAG else "HEAD" }}

build:
  number: 0
  string: {{ buildstr }}
  noarch: generic
  script: bash conda_recipe/build.sh

requirements:
  host:
    - bash
    - coreutils
    - python
    - pip
  run:
    - bash
    - coreutils
    - numpy=2.2.3
    - carveme=1.6.4
    - python >=3.10
    - pandas
    - cobra=0.29.1
    - diamond

test:
  source_files:
    - conda_recipe/run_test.sh
  commands:
    - bash conda_recipe/run_test.sh

about:
  home: https://github.com/ryanreyn/CarveWe
  license: GPL-3.0-only
  license_file: LICENSE
  summary: "Modular CLI for a custom metabolic model and media prediction workflow"
  description: |
    CarveWe provides a modular, well-documented Bash CLI that orchestrates
    genome-driven metabolic model building, annotation, growth simulation,
    and media prediction.
  dev_url: https://github.com/ryanreyn/CarveWe

extra:
  recipe-maintainers:
    - ryanreyn
