name: CI (smoke)

on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge,bioconda
          channel-priority: strict
          use-mamba: true
          activate-environment: build-carvewe

      - name: Export vars
        run: |
          echo "CARVEWE_GIT_REV=$GITHUB_SHA" >> $GITHUB_ENV
          echo "CONDA_PKG_VERSION=0.dev${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "PKG_BUILD_STRING=ci${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install build tools
        shell: bash -l {0}
        run: mamba install -y conda-build boa

      - name: Build (Linux)
        shell: bash -l {0}
        run: conda mambabuild conda_recipe

      - name: Resolve package path
        id: out
        shell: bash -l {0}
        run: echo "pkg=$(conda build conda_recipe --output)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-64-conda-pkg
          path: ${{ steps.out.outputs.pkg }}
          if-no-files-found: error
          retention-days: 7

      - name: Install & smoke test
        shell: bash -l {0}
        run: |
          PKG="${{ steps.out.outputs.pkg }}"
          mamba create -y -n smoke "$PKG"
          conda activate smoke
          carvewe --help >/dev/null
          genome-aligner --help >/dev/null
